[package]
name = "piston-example-freetype"
version = "0.1.0"
authors = ["eduardosalaz"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "piston-example-freetype"
path = "src/main.rs"


[dependencies]
piston = "0.49.0"
piston2d-opengl_graphics = "0.69.0"
piston2d-graphics = "0.35.0"
pistoncore-sdl2_window = "0.63.0"
freetype-rs = "0.23.0"
find_folder = "0.3.0"