/*Euler 2:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
WORKS SUCCESFULLY.
*/
fn main(){
    let mut a:u64 = 0;
    let mut b:u64 = 1;
    let mut c:u64 = 0;
    let mut sum:u64 = 0;
    while c < 4000000{
        c = a + b;
        a = b;
        b = c;
        if c % 2 == 0{
            sum += c;
        }
        else {

        }
    }
    println!("The sum of even Fibonacci terms below 4 million is {}", sum);
}